# Generated by Django 6.1.1 on 2026-09-10 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Army',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('primary_uniform_colour', models.CharField(max_length=10)),
                ('size', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Battalion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('size', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('rank', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Corp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('size', models.PositiveIntegerField()),
                ('affiliated_army', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET, to='application.army')),
                ('commander', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('size', models.PositiveIntegerField()),
                ('affiliated_corp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.corp')),
                ('commander', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('size', models.PositiveIntegerField()),
                ('affliated_battalion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.battalion')),
                ('commander', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Bridade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('size', models.PositiveIntegerField()),
                ('affilated_division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.division')),
                ('commander', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.personnel')),
            ],
        ),
        migrations.AddField(
            model_name='battalion',
            name='commander',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.personnel'),
        ),
        migrations.AddField(
            model_name='army',
            name='commander',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.personnel'),
        ),
        migrations.CreateModel(
            name='Regiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('size', models.PositiveIntegerField()),
                ('affilated_brigade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.bridade')),
                ('commander', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.personnel')),
            ],
        ),
        migrations.AddField(
            model_name='battalion',
            name='affliated_regiment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.regiment'),
        ),
    ]
